version: "3.7"

services:
    app:
        build: .
        container_name: check-update
        volumes:
            - .:/usr/app
        network_mode: "host"
        environment: 
            - DB_HOST=localhost
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - DB_PORT=20420
            - DB_DATABASE=check-version

volumes:
    pgdata:
        driver: local