version: "3.7"

services:
    app:
        build: .
        container_name: check-update
        volumes:
            - .:/usr/app
        network_mode: "host"

volumes:
    pgdata:
        driver: local