version: "3.7"

services:
    database:
        image: postgres
        container_name: database_postgres
        restart: always
        ports:
            - 5432:5432 
        environment:
            - POSTGRES_USER=check_version
            - POSTGRES_PASSWORD=123123
            - POSTGRES_DB=check-version
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: api-check-update-version
        ports: 
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on: 
            - database

volumes:
    pgdata:
        driver: local